
name: Minikube Access Check

on: [push]

jobs:
  minikube-setup-and-check:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
        
    - name: Check Minikube Status
      run: |
        minikube status
        
    - name: Get Nodes
      run: |
        kubectl get nodes
        
    - name: Install Helm Diff Plugin
      run: |
        helm plugin install https://github.com/databus23/helm-diff || true # Avoid failing if already installed
  
    - name: Check Helm Release "my-dynatrace-operator"
      run: |        
        helm diff release my-dynatrace-operator --namespace dynatrace-helm -f values.yaml
