
name: Minikube Access Check

on: [push]

jobs:
  minikube-setup-and-check:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
        
    - name: Check Minikube Status
      run: |
        minikube status
        
    - name: Get Nodes
      run: |
        kubectl get nodes

    - name: Check Helm Releases in All Namespaces
      run: |
        helm list --all-namespaces        