
name: Minikube Access Check

on: [push]

jobs:
  minikube-setup-and-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    # - name: Install Minikube
    #   run: |
    #     curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    #     sudo install minikube-linux-amd64 /usr/local/bin/minikube
        
    # - name: Start Minikube
    #   run: |
    #     minikube start --driver=docker
        
    - name: Check Minikube Status
      run: |
        minikube status
        
    - name: Get Nodes
      run: |
        kubectl get nodes